language: java

jdk:
  - oraclejdk8

install:
    - git clone http://github.com/Spirals-Team/jPerturb.git
    - cd jPerturb
    - mvn install
    - cd ..
    - wget https://gforge.inria.fr/frs/download.php/latestzip/86/Spoon-latest.zip
    - unzip Spoon-latest.zip

script:
    - java -classpath spoon-core-5.1.0-jar-with-dependencies.jar:jPerturb/target/jPerturb-0.0.1-SNAPSHOT.jar spoon.Launcher -i resources/:jPerturb/src/main/java/perturbation/ -o src/main/java --with-imports --compile -d bin -p processor.AssignmentProcessor:processor.VariableCaster:processor.PerturbationProcessor
    - javac -d bin -cp bin src/main/java/*/*.java
    - travis_wait java -cp bin experiment.Runner
    - git diff | wc -l

